const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const panels=['setup','listen','diagnose','experiment','pressure','reflect','complete'];
const fundamentals=['Pitch','Fingering','Rhythm','Movement','Structure','Harmony','Inflection','Articulation / touch','Balance / voicing','Dynamics','Pedaling','Learning / memory'];
const exercises={
  'Pitch':['Name, then place','Say each pitch before playing it. Pause long enough to choose; do not let the fingers guess.','Every note is consciously named before it sounds.'],
  'Fingering':['Write the choreography','Choose and say every finger aloud. For hands together, pair them as one combined number.','The same planned fingers arrive without correction.'],
  'Rhythm':['Make the pulse visible','Tap the pulse, speak the rhythm, then play the chunk once without stopping.','The pulse continues through the difficult event.'],
  'Movement':['Exaggerate the preparation','Slow down and deliberately prepare the next hand shape or release early. Make the gesture obvious.','You can name when the movement begins—not only where it ends.'],
  'Structure':['Find the pattern','Mark what repeats, answers, or changes. Play the matching fragments back to back.','You can explain the relationship before playing.'],
  'Harmony':['Compress the notes','Name the chord or harmonic direction, then play it as a block before restoring the texture.','You know where the harmony is going.'],
  'Inflection':['Shape one destination','Choose the arrival note and exaggerate the direction toward and away from it.','The phrase has one clearly heard destination.'],
  'Articulation / touch':['Reverse the touch','Change one articulation: try staccato where it is legato, or give each hand a different touch.','The variation reveals which voice must stay continuous.'],
  'Balance / voicing':['Reverse the balance','Bring out the supporting voice and quiet the melody, then restore the intended balance.','Each layer can be controlled independently.'],
  'Dynamics':['Train the boundary','Play once extremely softly, then once with full sound, without changing tempo.','Control survives at both dynamic extremes.'],
  'Pedaling':['Pedal every event','Change pedal on every note or harmony as an overtraining exercise, listening for each release.','Every pedal change is intentional and clean.'],
  'Learning / memory':['Active recall','Study the tiny chunk, hide the score, attempt it, then return only to answer the exact gap.','You can begin from memory without reconstructing from momentum.']
};
let state={piece:'',key:'',timeSignature:'4/4',range:null,section:'',goal:'',spots:[],selectedSpot:null,fundamental:null,chunk:'1 transition',reps:0,pressure:'',notices:[]};
let seconds=0,timerId=null;
function show(name,step){panels.forEach(p=>$(`#${p}Panel`)?.classList.toggle('hidden',p!==name));if(step){$$('.step').forEach(x=>x.classList.toggle('active',+x.dataset.step===step));}}
function getPieceLibrary(){const saved=JSON.parse(localStorage.getItem('cadencePieces')||'{}');const history=JSON.parse(localStorage.getItem('cadenceSessions')||'[]');history.forEach(s=>{if(s.piece&&!saved[s.piece])saved[s.piece]={key:s.key||'',timeSignature:s.timeSignature||'4/4'}});return saved}
function renderPieceHistory(){const library=getPieceLibrary();$('#pieceHistory').innerHTML='';Object.keys(library).sort().forEach(name=>{const option=document.createElement('option');option.value=name;$('#pieceHistory').append(option)})}
function restorePieceDetails(){const match=getPieceLibrary()[$('#pieceInput').value.trim()];if(!match)return;$('#keyInput').value=match.key||'';$('#timeSignatureInput').value=match.timeSignature||'4/4';updateBeatOptions(true)}
function updateBeatOptions(resetEnd=false){const count=Math.max(1,parseInt($('#timeSignatureInput').value,10)||4);const from=$('#fromBeatInput'),to=$('#toBeatInput'),oldFrom=+from.value||1,oldTo=+to.value||count;const options=Array.from({length:count},(_,i)=>`<option value="${i+1}">${i+1}</option>`).join('');from.innerHTML=options;to.innerHTML=options;from.value=String(Math.min(oldFrom,count));to.value=String(resetEnd?count:Math.min(oldTo,count));$('#beatHint').textContent=`${$('#timeSignatureInput').value} provides ${count} beat positions per measure. The range defaults from beat 1 to beat ${count}.`}
function savePieceMetadata(){const library=getPieceLibrary();library[state.piece]={key:state.key,timeSignature:state.timeSignature};localStorage.setItem('cadencePieces',JSON.stringify(library));renderPieceHistory()}
function setSession(){state.piece=$('#pieceInput').value.trim()||'Untitled piece';state.key=$('#keyInput').value.trim();state.timeSignature=$('#timeSignatureInput').value;state.range={from:{measure:+$('#fromMeasureInput').value||1,beat:+$('#fromBeatInput').value||1},to:{measure:+$('#toMeasureInput').value||1,beat:+$('#toBeatInput').value||1}};if(state.range.to.measure<state.range.from.measure){state.range.to.measure=state.range.from.measure;$('#toMeasureInput').value=state.range.to.measure}state.section=`m. ${state.range.from.measure} b. ${state.range.from.beat} → m. ${state.range.to.measure} b. ${state.range.to.beat}`;state.goal=$('#goalInput').value.trim()||'Build reliable control';savePieceMetadata();$('#pieceDisplay').textContent=state.piece;$('#goalDisplay').textContent=[[state.key,state.timeSignature].filter(Boolean).join(' · '),state.section,state.goal].filter(Boolean).join(' · ');$('#sessionLabel').textContent=state.section;show('listen',1)}
function tick(){seconds++;$('#timer').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}
function toggleTimer(){if(timerId){clearInterval(timerId);timerId=null;$('#timerButton').classList.remove('running');$('#timerHint').textContent='Good. Mark what you noticed, then continue.';$('#finishPlaythrough').classList.remove('hidden')}else{timerId=setInterval(tick,1000);$('#timerButton').classList.add('running');$('#timerHint').textContent='Keep going. Notice, don’t correct.'}}
function renderSpots(){const list=$('#spotList');list.innerHTML='';state.spots.sort((a,b)=>b.severity-a.severity).forEach((s,i)=>{const el=document.createElement('button');el.className='spot-item'+(state.selectedSpot===i?' selected':'');el.innerHTML=`<span class="stars">${'★'.repeat(s.severity)}</span><p>${s.location}<br><small>${s.notice||'Observed in playthrough'}</small></p><span>→</span>`;el.onclick=()=>{state.selectedSpot=i;renderSpots();$('#chooseSpot').disabled=false};list.append(el)})}
function updateCoach(){if(!state.fundamental)return;const [title,text,success]=exercises[state.fundamental];$('#exerciseTitle').textContent=title;$('#exerciseText').textContent=`On ${state.chunk}, ${text.charAt(0).toLowerCase()+text.slice(1)}`;$('#successText').textContent=success;$('#playRep').disabled=false}
function finishRep(result){state.reps++;$('#repCount').textContent=state.reps;$('#repBadge').textContent=`Rep ${String(state.reps+1).padStart(2,'0')}`;$('#evaluation').classList.add('hidden');if(result==='struggle'){state.chunk='4 notes';$$('#chunkOptions button').forEach(b=>b.classList.toggle('active',b.dataset.value==='4 notes'));$('#exerciseTitle').textContent='Reduce the load';$('#exerciseText').textContent='Make the chunk smaller, slow down, or separate the hands. Keep the same question.';$('#successText').textContent='You can proceed without losing the plan.'}else if(result==='adapting'){$('#exerciseTitle').textContent='Repeat with new awareness';$('#exerciseText').textContent='Keep the setup. On this attempt, direct attention to the exact event that just failed.';$('#successText').textContent='The same event becomes more predictable.'}else{show('pressure',4)}}
function startFresh(){state={piece:'',key:'',timeSignature:'4/4',range:null,section:'',goal:'',spots:[],selectedSpot:null,fundamental:null,chunk:'1 transition',reps:0,pressure:'',notices:[]};seconds=0;clearInterval(timerId);timerId=null;$('#timer').textContent='00:00';$('#repCount').textContent='0';$$('input,textarea').forEach(el=>{if(el.type!=='checkbox')el.value=''});$('#fromMeasureInput').value=1;$('#toMeasureInput').value=1;$('#timeSignatureInput').value='4/4';renderPieceHistory();updateBeatOptions(true);show('setup');$('#hero').classList.add('hidden');$('#workspace').classList.remove('hidden')}
$('#beginButton').onclick=startFresh;$('#newSession').onclick=startFresh;$('#startPlaythrough').onclick=setSession;$('#timerButton').onclick=toggleTimer;
$('#timeSignatureInput').onchange=()=>updateBeatOptions(true);$('#pieceInput').onchange=restorePieceDetails;$('#pieceInput').oninput=restorePieceDetails;
$$('.notice-chip').forEach(b=>b.onclick=()=>{b.classList.toggle('selected');state.notices=b.classList.contains('selected')?[...state.notices,b.dataset.notice]:state.notices.filter(x=>x!==b.dataset.notice)});
$('#finishPlaythrough').onclick=()=>show('diagnose',2);
$('#spotForm').onsubmit=e=>{e.preventDefault();state.spots.push({location:$('#locationInput').value.trim(),severity:+$('#severityInput').value,notice:state.notices[0]});$('#locationInput').value='';state.selectedSpot=0;renderSpots();$('#chooseSpot').disabled=false};
$('#chooseSpot').onclick=()=>{$('#activeSpotTitle').textContent=`Solve ${state.spots[state.selectedSpot].location}.`;show('experiment',3)};
const f=$('#fundamentals');fundamentals.forEach(name=>{const b=document.createElement('button');b.textContent=name;b.onclick=()=>{state.fundamental=name;$$('#fundamentals button').forEach(x=>x.classList.toggle('active',x===b));updateCoach()};f.append(b)});
$$('#chunkOptions button').forEach(b=>b.onclick=()=>{state.chunk=b.dataset.value;$$('#chunkOptions button').forEach(x=>x.classList.toggle('active',x===b));updateCoach()});
$('#playRep').onclick=()=>{$('#evaluation').classList.remove('hidden');$('#evaluation').scrollIntoView({behavior:'smooth',block:'center'})};
$$('.result-buttons button').forEach(b=>b.onclick=()=>finishRep(b.dataset.result));
$$('.comparison button').forEach(b=>b.onclick=()=>{state.pressure=b.dataset.pressure;$('#summaryReps').textContent=state.reps;$('#summaryFocus').textContent=state.fundamental||'—';$('#summaryPressure').textContent={weaker:'Less secure',same:'About the same',better:'Clearly better'}[state.pressure];show('reflect',5)});
$('#saveSession').onclick=()=>{const history=JSON.parse(localStorage.getItem('cadenceSessions')||'[]');history.unshift({...state,reflection:$('#reflectionInput').value,date:new Date().toISOString(),review:$('#reviewCheck').checked});localStorage.setItem('cadenceSessions',JSON.stringify(history.slice(0,30)));show('complete')};
$('#resetButton').onclick=()=>{if(confirm('End this session and return home?')){location.reload()}};
$('#soundToggle').onclick=e=>{e.currentTarget.textContent=e.currentTarget.textContent==='♪'?'♩':'♪';e.currentTarget.setAttribute('aria-label',e.currentTarget.textContent==='♪'?'Mute sound':'Enable sound')};
